// <auto-generated />
using System;
using IntihalProjesi.Repositories.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntihalProjesi.Migrations
{
    [DbContext(typeof(OrjinalIntihalDbContext))]
    partial class OrjinalIntihalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntihalProjesi.Models.BenzerlikSonucu", b =>
                {
                    b.Property<int>("SonucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SonucId"));

                    b.Property<double>("BenzerlikOrani")
                        .HasColumnType("float");

                    b.Property<int>("IkinciDosyaId")
                        .HasColumnType("int");

                    b.Property<int>("IlkDosyaId")
                        .HasColumnType("int");

                    b.HasKey("SonucId");

                    b.HasIndex("IkinciDosyaId");

                    b.HasIndex("IlkDosyaId");

                    b.ToTable("BenzerlikSonuclari");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Dosya", b =>
                {
                    b.Property<int>("DosyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DosyaId"));

                    b.Property<string>("CleanedPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IcerikId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("DosyaId");

                    b.HasIndex("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Icerik", b =>
                {
                    b.Property<int>("IcerikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcerikId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("IcerikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Icerikler");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("IntihalProjesi.Models.BenzerlikSonucu", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Dosya", "IkinciDosya")
                        .WithMany()
                        .HasForeignKey("IkinciDosyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntihalProjesi.Models.Dosya", "IlkDosya")
                        .WithMany()
                        .HasForeignKey("IlkDosyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IkinciDosya");

                    b.Navigation("IlkDosya");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Dosya", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Icerik", "Icerik")
                        .WithMany("Dosyalar")
                        .HasForeignKey("IcerikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntihalProjesi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Icerik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Icerik", b =>
                {
                    b.HasOne("IntihalProjesi.Models.Kullanici", "Kullanici")
                        .WithMany("Icerikler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Icerik", b =>
                {
                    b.Navigation("Dosyalar");
                });

            modelBuilder.Entity("IntihalProjesi.Models.Kullanici", b =>
                {
                    b.Navigation("Icerikler");
                });
#pragma warning restore 612, 618
        }
    }
}
